// Generated by BUCKLESCRIPT VERSION 1.7.1, PLEASE EDIT WITH CARE
'use strict';

var React      = require("react");
var ReactDOMRe = require("reason-react/lib/js/src/reactDOMRe.js");

ReactDOMRe.renderToElementWithId(React.createElement("h1", undefined, "Hello World"), "root");

/*  Not a pure module */
