// Generated by BUCKLESCRIPT VERSION 1.7.1, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

console.log("hello!");

function twice_more(x) {
  return (x << 1);
}

function print_twice_more(x) {
  return Pervasives.print_int((x << 1));
}

Pervasives.print_int(20);

exports.twice_more       = twice_more;
exports.print_twice_more = print_twice_more;
/*  Not a pure module */
